import { EmpruntCurrent } from "@/components/empruntCurrent";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { LoginForm } from "@/components/login-form";
import { SideBar } from "@/components/sideBar";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "library",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const genres = await prisma.books.findMany({
    select: {
      types: true,
    },
  });

  console.log(session);

  const arrayGenres = Array.from(genres, (g) => g.types);

  const data = [...new Set(arrayGenres)];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <div className="relative flex min-h-svh flex-col bg-background">
          <div className="flex flex-col">
            <main className="flex flex-col">
              <Header />
              <div className="container flex items-start">
                {session ? <SideBar items={data} /> : ""}
                <div className="relative lg:gap-10 lg:py-8">
                  <div className="w-full min-w-0 max-w-3xl">
                    {session ? children : <LoginForm />}
                    {session ? (
                      <EmpruntCurrent userEmail={session?.user?.email} />
                    ) : (
                      ""
                    )}
                  </div>
                </div>
              </div>
            </main>
            <Footer />
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
